# -*- coding: utf-8 -*-
#
# Created by Alex Molina
# sept 2021
# 
# The code is licensed under the MIT License - see the LICENSE file for details.
# Copyright (c) 2021 Alejandro Molina Villegas

import os
import re
from os.path import (join, exists, dirname, abspath)
from pathlib import Path

# Setting important paths relative to this file location and file names
PROJECT_ROOT = str(Path(dirname(abspath(__file__))))
MODELS_PATH = join(PROJECT_ROOT,"application/models/")
SUBWORDS_ENCODER_PATH = join(MODELS_PATH, "subpal_encoder")
ClASSIFICATION_MODEL_PATH = join(MODELS_PATH, "CNN_locatel_weights3")

# CNN settings
PADDING_MAX_LEN = 334

# full category names
CATEGORIES = ["ALARMAS VECINALES",
"ALERTA SISMICA",
"ALUMBRADO",
"APOYO SERVICIOS FUNERARIOS",
"ASESORÍA DE TERCEROS ACREDITADOS",
"ASESORÍA JURÍDICA",
"ASISTENCIA SOCIAL",
"ASISTENCIA VETERINARIA",
"BACHEO",
"BALIZAMIENTO",
"BARBECHO / CHAPONEO",
"BECAS",
"COVID",
"CRÉDITO DE VIVIENDA",
"DESAZOLVE",
"FALTA DE AGUA",
"FUGA DE AGUA",
"LIMPIEZA VIA PUBLICA",
"LLAVE CDMX",
"MANTENIMIENTO DE COLADERA / ALCANTARILLA",
"MANTENIMIENTO DRENAJE",
"MANTENIMIENTO PARQUE / AREA VERDE",
"MANTENIMIENTO SEMÁFOROS",
"MANTENIMIENTO VÍA PÚBLICA",
"PAVIMENTACION",
"PODA / RETIRO ARBOL",
"PROGRAMA APOYO A CUIDADORES",
"PROTECCION CIVIL",
"QUEJA DE TRANSPORTE PUBLICO",
"QUEJA FUNCIONARIO",
"RECOLECCIÓN BASURA",
"REGISTRO FERIAS INDIGENAS",
"REINSCRIPCION AL CENDI",
"REPARACION DE EMPEDRADO",
"RETIRO AMBULANTE",
"RETIRO CASCAJO, ESCOMBRO, AZOLVE, RAMAS",
"SOLICITU DE AUDIENCIA",
"SOLICITUD DE CONCERTACIÓN VECINAL",
"SOLICITUD DE VIGILANCIA",
"SOLICITUD DE VOLANTEO",
"SOLICITUD ESTUDIO SOCIOECONOMICO",
"SOLICITUD EVALUACIÓN DE RIESGO",
"SOLICITUD/SEGURO DE DESEMPLEO",
"TRAMITES / INFO VEHICULAR",
"USO DE SUELO",
"VEHÍCULO ABANDONADO / CHATARRIZACIÓN",
"VENTA DE ALCOHOL / DROGA",
"VERIFICACIÓN ADMINISTRATIVA"]

NB_CLASSES = len(CATEGORIES)

class Config:
    """Set Flask configuration vars"""
    # General
    TESTING = True
    DEBUG = True
